FROM node:22 AS builder

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma
COPY prisma.config.ts ./prisma.config.ts

RUN npm install

COPY . .

RUN npx prisma generate

RUN npm run build


# // runner
FROM node:22 AS runner

WORKDIR /app

COPY --from=builder /app .

CMD ["npm","start"]