services:
  nextjs:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    volumes:
      - .:/app
      - /app/node_modules
    command: >
      sh -c "npx prisma generate && npm run dev"
    restart: unless-stopped