FROM node:22 AS builder

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma
COPY prisma.config.ts ./prisma.config.ts

RUN npm ci

COPY . .

RUN npx prisma generate

RUN npm run build


# runner
FROM node:22-slim AS runner

WORKDIR /app

ENV NODE_ENV=production


COPY --from=builder /app/package*.json ./
RUN npm ci --only=production && npm cache clean --force


COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/prisma.config.ts ./prisma.config.ts

EXPOSE 3000

CMD ["npm", "start"]
